# usecase/ports.py
# 포트 인터페이스 (Repository 추상 계층)
# PRG-ID: 전체 (Clean Architecture usecase ↔ adapter 경계)
from abc import ABC, abstractmethod
from typing import Optional

from backend.domain.entities import (
    Answer, AnswerGroup, AnswerGroupItem, AnswerVote,
    Book, BookStep, BookmarkAnswer, Insight, Meeting,
    NewQuestion, OneLineReview, Participant, Poll, PollOption,
    PollVote, Question, ReadingLetter, Retrospective,
    SpeakerSelection, Step, Timer, Topic, TopicBook,
)


class ITopicRepository(ABC):
    @abstractmethod
    def list_all(self, meeting_id: int) -> list[Topic]: ...
    @abstractmethod
    def get(self, topic_id: int) -> Optional[Topic]: ...
    @abstractmethod
    def create(self, topic: Topic) -> Topic: ...
    @abstractmethod
    def update(self, topic: Topic) -> Topic: ...
    @abstractmethod
    def delete(self, topic_id: int) -> None: ...
    @abstractmethod
    def list_steps(self, topic_id: int) -> list[Step]: ...
    @abstractmethod
    def get_step(self, step_id: int) -> Optional[Step]: ...
    @abstractmethod
    def create_step(self, step: Step) -> Step: ...
    @abstractmethod
    def update_step(self, step: Step) -> Step: ...
    @abstractmethod
    def delete_step(self, step_id: int) -> None: ...
    @abstractmethod
    def assign_book_to_step(self, book_step: BookStep) -> BookStep: ...
    @abstractmethod
    def remove_book_from_step(self, book_id: int, step_id: int) -> None: ...


class IBookRepository(ABC):
    @abstractmethod
    def list_active(self) -> list[Book]: ...
    @abstractmethod
    def get(self, book_id: int) -> Optional[Book]: ...
    @abstractmethod
    def create(self, book: Book) -> Book: ...
    @abstractmethod
    def update(self, book: Book) -> Book: ...
    @abstractmethod
    def soft_delete(self, book_id: int) -> None: ...
    @abstractmethod
    def has_answers(self, book_id: int) -> bool: ...


class IQuestionRepository(ABC):
    @abstractmethod
    def list_by_book(self, book_id: int) -> list[Question]: ...
    @abstractmethod
    def get(self, question_id: int) -> Optional[Question]: ...
    @abstractmethod
    def create(self, question: Question) -> Question: ...
    @abstractmethod
    def update(self, question: Question) -> Question: ...
    @abstractmethod
    def soft_delete(self, question_id: int) -> None: ...


class IAnswerRepository(ABC):
    @abstractmethod
    def get(self, answer_id: int) -> Optional[Answer]: ...
    @abstractmethod
    def get_by_question_participant(self, question_id: int, participant_id: int) -> Optional[Answer]: ...
    @abstractmethod
    def list_by_question(self, question_id: int) -> list[Answer]: ...
    @abstractmethod
    def create(self, answer: Answer) -> Answer: ...
    @abstractmethod
    def update(self, answer: Answer) -> Answer: ...
    @abstractmethod
    def count_by_book(self, book_id: int) -> int: ...


class IAnswerVoteRepository(ABC):
    @abstractmethod
    def get(self, answer_id: int, participant_id: int) -> Optional[AnswerVote]: ...
    @abstractmethod
    def upsert(self, vote: AnswerVote) -> AnswerVote: ...
    @abstractmethod
    def delete(self, answer_id: int, participant_id: int) -> None: ...
    @abstractmethod
    def count_by_answer(self, answer_id: int) -> dict[str, int]: ...


class IAnswerGroupRepository(ABC):
    @abstractmethod
    def list_by_meeting(self, meeting_id: int) -> list[AnswerGroup]: ...
    @abstractmethod
    def create(self, group: AnswerGroup) -> AnswerGroup: ...
    @abstractmethod
    def add_item(self, item: AnswerGroupItem) -> AnswerGroupItem: ...
    @abstractmethod
    def remove_item(self, group_id: int, answer_id: int) -> None: ...
    @abstractmethod
    def list_items(self, group_id: int) -> list[AnswerGroupItem]: ...


class IMeetingRepository(ABC):
    @abstractmethod
    def get(self, meeting_id: int) -> Optional[Meeting]: ...
    @abstractmethod
    def get_by_code(self, code: str) -> Optional[Meeting]: ...
    @abstractmethod
    def create(self, meeting: Meeting) -> Meeting: ...
    @abstractmethod
    def update(self, meeting: Meeting) -> Meeting: ...


class IParticipantRepository(ABC):
    @abstractmethod
    def get(self, participant_id: int) -> Optional[Participant]: ...
    @abstractmethod
    def get_by_meeting_nickname(self, meeting_id: int, nickname: str) -> Optional[Participant]: ...
    @abstractmethod
    def list_by_meeting(self, meeting_id: int) -> list[Participant]: ...
    @abstractmethod
    def create(self, participant: Participant) -> Participant: ...
    @abstractmethod
    def count_by_meeting(self, meeting_id: int) -> int: ...


class ITimerRepository(ABC):
    @abstractmethod
    def get_by_meeting(self, meeting_id: int) -> Optional[Timer]: ...
    @abstractmethod
    def create(self, timer: Timer) -> Timer: ...
    @abstractmethod
    def update(self, timer: Timer) -> Timer: ...


class IPollRepository(ABC):
    @abstractmethod
    def get(self, poll_id: int) -> Optional[Poll]: ...
    @abstractmethod
    def list_by_meeting(self, meeting_id: int) -> list[Poll]: ...
    @abstractmethod
    def create(self, poll: Poll, options: list[PollOption]) -> Poll: ...
    @abstractmethod
    def close(self, poll_id: int, closed_at: str) -> Poll: ...
    @abstractmethod
    def vote(self, vote: PollVote) -> PollVote: ...
    @abstractmethod
    def get_vote(self, poll_id: int, participant_id: int) -> Optional[PollVote]: ...
    @abstractmethod
    def list_active_polls_state(self, meeting_id: int) -> list[dict]: ...


class ISpeakerRepository(ABC):
    @abstractmethod
    def list_by_meeting(self, meeting_id: int) -> list[SpeakerSelection]: ...
    @abstractmethod
    def create(self, selection: SpeakerSelection) -> SpeakerSelection: ...
    @abstractmethod
    def get_latest(self, meeting_id: int) -> Optional[SpeakerSelection]: ...


class IRetrospectiveRepository(ABC):
    @abstractmethod
    def get_by_meeting(self, meeting_id: int) -> Optional[Retrospective]: ...
    @abstractmethod
    def create(self, retro: Retrospective) -> Retrospective: ...
    @abstractmethod
    def add_insight(self, insight: Insight) -> Insight: ...
    @abstractmethod
    def add_bookmark(self, bookmark: BookmarkAnswer) -> BookmarkAnswer: ...
    @abstractmethod
    def remove_bookmark(self, retro_id: int, answer_id: int) -> None: ...
    @abstractmethod
    def add_new_question(self, nq: NewQuestion) -> NewQuestion: ...
    @abstractmethod
    def get_one_line_review(self, retro_id: int, participant_id: int) -> Optional[OneLineReview]: ...
    @abstractmethod
    def add_one_line_review(self, review: OneLineReview) -> OneLineReview: ...
    @abstractmethod
    def update_one_line_review(self, review: OneLineReview) -> OneLineReview: ...
    @abstractmethod
    def get_full(self, meeting_id: int) -> Optional[Retrospective]: ...


class ITopicBookRepository(ABC):
    @abstractmethod
    def list_by_topic(self, topic_id: int) -> list[TopicBook]: ...
    @abstractmethod
    def get(self, topic_book_id: int) -> Optional[TopicBook]: ...
    @abstractmethod
    def get_by_topic_and_order(self, topic_id: int, order_num: int) -> Optional[TopicBook]: ...
    @abstractmethod
    def get_by_topic_and_book(self, topic_id: int, book_id: int) -> Optional[TopicBook]: ...
    @abstractmethod
    def create(self, topic_book: TopicBook) -> TopicBook: ...
    @abstractmethod
    def update_status(self, topic_book_id: int, status: str) -> TopicBook: ...
    @abstractmethod
    def count_completed(self, topic_id: int) -> int: ...


class IReadingLetterRepository(ABC):
    @abstractmethod
    def get(self, topic_id: int, participant_id: int) -> Optional[ReadingLetter]: ...
    @abstractmethod
    def create(self, letter: ReadingLetter) -> ReadingLetter: ...
    @abstractmethod
    def list_by_topic(self, topic_id: int) -> list[ReadingLetter]: ...
